# Generated by Django 4.2.13 on 2024-05-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_task_unblocked_at'),
        ('r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPackageRepositoryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='r.rpackage')),
                ('repository_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repositoryversion')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('package', 'repository_version')},
            },
        ),
    ]
