# Generated by Django 4.2.13 on 2024-05-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_task_core_task_unblock_2276a4_idx_and_more'),
        ('r', '0003_rpublishedmetadata_rpackage_md5sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
    ]
